#!/bin/bash

# Copyright (C) 2017 binsec GmbH <info@binsec.com>
# 
# This library is free software; you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the Free
# Software Foundation; version 2.1 only.
# 
# This library is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public License along
# with this library; if not, write to the Free Software Foundation, Inc., 51
# Franklin St, Fifth Floor, Boston, MA 02110, USA
# Add modprobe rbd to rc.modules

echo "Adding rbd to rc.modules"
#Check if its already there
if [ -e "/etc/rc.modules" ]
then
  #File exists, check if we have an entry for rbd
  grep "modprobe rbd" /etc/rc.modules
  rc = $?
  if [[ $rc == 1 ]]
  then
    echo "\nmodprobe rbd\n" >> /etc/rc.modules
    chmod 0744 /etc/rc.modules
  fi
else
  #File doesn't exist, no need to check for entry
  echo "modprobe rbd" > /etc/rc.modules
  chmod 0744 /etc/rc.modules
fi

echo "Load rbd module"
modprobe rbd

echo "Saving original lvm config"
cp /etc/lvm/lvm.conf /etc/lvm/lvm.conf.original
echo "Patching lvm config"
patch /etc/lvm/lvm.conf patches/lvm7.patch

echo "Saving original lvm master config"
cp /etc/lvm/master/lvm.conf /etc/lvm/master/lvm.conf.original
echo "Patching lvm master config"
patch /etc/lvm/master/lvm.conf patches/lvm-master7.patch

echo "Installing LVHDoRBDSR.py"
install -m 755 src/LVHDoRBDSR.py /opt/xensource/sm/
ln -s /opt/xensource/sm/LVHDoRBDSR.py /opt/xensource/sm/LVMoRBDSR

echo "Activate rbd as sm-plugin"
cp /etc/xapi.conf /etc/xapi.conf.orig
sed -i '/^sm-plugins/ s/$/ lvmorbd/' /etc/xapi.conf

echo "LVMoRBDSR driver installed, please run xe-toolkit-restart for activation"
exit 0
